platform :ios, '10.0'

target 'react-native-zip-stream' do
  # Pods for react-native-zip-stream
  pod 'ZipArchive'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
